name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy to Azure Static Web App

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # This must match the secret name you created
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_GRASS_0C460D003 }}

          # Where your source files are located
          # If your index.html and style.css are at the root, use "/" 
          app_location: "/"

          # No build step is needed for just HTML/CSS; set output_location to "/"
          output_location: "/"

          # By default, this action tries to build a project.
          # If you only have static files, you can explicitly skip the build step like so:
          skip_app_build: true
